apiVersion: v1
kind: Pod
metadata:
  name: backend-one
  labels:
    app.kubernetes.io/name: backend-one
spec:
  containers:
  - name: backend-one
    image: kube_services-books:latest
    imagePullPolicy: Never
    ports:
      - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: backend-one
spec:
  selector:
    app.kubernetes.io/name: backend-one
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-two
  labels:
    app.kubernetes.io/name: backend-two
spec:
  containers:
  - name: backend-two
    image: kube_services-movies:latest
    imagePullPolicy: Never
    ports:
      - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: backend-two
spec:
  selector:
    app.kubernetes.io/name: backend-two
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
---
apiVersion: v1
kind: Pod
metadata:
  name: middle-layer
  labels:
    app.kubernetes.io/name: middle-layer
spec:
  containers:
    - env:
        - name: BOOKS_HOST
          value: http://backend-one:3003
        - name: MOVIES_HOST
          value: http://backend-two:3004
      name: middle-layer
      image: middle-layer
      imagePullPolicy: Never
      ports:
        - containerPort: 3005
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: middle-layer
spec:
  selector:
    app.kubernetes.io/name: middle-layer
  ports:
    - protocol: TCP
      port: 3005
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  containers:
    - env:
        - name: MIDDLE_HOST
          value: http://middle-layer:3005
      name: frontend
      image: frontend
      imagePullPolicy: Never
      ports:
        - containerPort: 3006
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - protocol: TCP
      port: 3006
